
package pe.edu.idat.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.9
 * Sat May 07 19:56:06 COT 2022
 * Generated source version: 2.5.9
 */

@XmlRootElement(name = "findByCorDResponse", namespace = "http://ws.idat.edu.pe/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findByCorDResponse", namespace = "http://ws.idat.edu.pe/")

public class FindByCorDResponse {

    @XmlElement(name = "return")
    private java.util.Collection<pe.edu.idat.vo.PersonalVO> _return;

    public java.util.Collection<pe.edu.idat.vo.PersonalVO> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.Collection<pe.edu.idat.vo.PersonalVO> new_return)  {
        this._return = new_return;
    }

}

